name: Kakao Map Components Tests

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: dist
          path: dist/
          retention-days: 1

  cypress-run:
    needs: lint-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        id: download
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: dist
          path: dist/

      - name: Build (only if artifact download failed)
        if: steps.download.outcome == 'failure'
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run serve
          wait-on: "http://localhost:8080"
        env:
          KAKAO_MAP_API_KEY: ${{ secrets.KAKAO_MAP_API_KEY }}
